services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: bookio
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    


networks:
  spring-demo: 
    driver: bridge

volumes:
  postgres:
    driver: local