spring:
  datasource:
    url: jdbc:postgressql://localhost:5232/bookio
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: ryan
    password: ryan
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
